### ISSUE TITLE
NGRX

### ISSUE THREAD

**Issue by samvloeberghs** [manfredsteyer/angular-crud#4]
Hi @manfredsteyer do you think NGRX has a place inside this project?
What do you think?

**Comment by manfredsteyer** [comment]
Hi Sam,
sorry for this late response. I lost track of this message.

Yes, NGRX has a place within this. I think we should define a flag within the model-files, whether to use NGRX. We can do the same with other libs, like Angular Material etc.

What do you think?

Would you like to contribute?

Btw: John Papa and Ward Bell are working on a solution to make CRUD and NGRX more easy. Perhaps we could integrate those libs as well.

Best wishes,
Manfred

**Comment by mraible** [comment]
Closing because this issue has gone stale.
