### ISSUE TITLE
Error: Schematic "crud-module" not found in collection "@schematics/angular".

### ISSUE THREAD

**Issue by mike-boddin** [manfredsteyer/angular-crud#9]
When I step through the Tutorial I get stuck at 
4.) `ng g crud-module hotel --collection angular-crud `
with error:

`Error: Schematic "crud-module" not found in collection "@schematics/angular".`

When I add `@schematics/angular` dependency explicitly, I get the following error:

`Cannot find module '@schematics/angular/utility/parse-name'`

Any suggestions on this?
Thanks in advance!

**Comment by mraible** [comment]
You need to run:

    ng g angular-crud:crud-module hotel
